allowBuilds:
  '@google/genai': false
  protobufjs: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.117.2'
  - '@supabase/functions-js@2.117.2'
  - '@supabase/postgrest-js@2.117.2'
  - '@supabase/realtime-js@2.117.2'
  - '@supabase/storage-js@2.117.2'
  - '@supabase/supabase-js@2.117.2'
