[env:romi-devkit-v1]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  madhephaestus/ESP32Servo@^3.0.6
